[package]
name = "hooking_macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "hooking libs in rust"
readme = "../README.md"
repository = "https://github.com/pigeonhands/hooking-rs"

[dependencies]
